Add web-embed example using web elements
formsort/oss pull request #30
Opened 2021-09-14 18:36 UTC by lizraeli

- Create an `examples` subfolder in the `web-embed` folder
- Add an example using web components via [lit](https://lit.dev/).
- The example embeds a flow within a web page (client, flow, and variant name provided via `.env` file), registers listeners for all event types (analytics events and redirect event), and logs all events with their payloads onto the page. 

### Screenshot
<img width="338" alt="Screen Shot 2021-09-14 at 2 31 13 PM" src="https://user-images.githubusercontent.com/12574319/133314266-56f3b8ae-d1ea-4224-a0bf-0c78d21adee3.png">

2021-09-15 12:26 UTC, alikirec requested changes
it seems we need to add `parcel` as a global dependency to run the example project, we should add an instruction to readme or add `parcel` as a local dependency

2021-09-15 12:26 UTC, alikirec commented on packages/web-embed-api/examples/web-components/lit/index.ts
> +    const formsortEbmedElem = this.formsortEmbedRef.value!;
typo `formsortEmbedElem`

2021-09-15 12:33 UTC, alikirec commented on packages/web-embed-api/examples/web-components/lit/index.html
> +    <script src="./index.ts"></script>
I tried it on my local and got an error, I think we need to add `type="modulo"` here, see the related [issue](https://github.com/fregante/browser-extension-template/issues/51) 
```suggestion
    <script type="module" src="./index.ts"></script>
```

2021-09-16 15:36 UTC, lizraeli commented on packages/web-embed-api/examples/web-components/lit/index.ts
> +    const formsortEbmedElem = this.formsortEmbedRef.value!;
fixed

2021-09-16 15:37 UTC, lizraeli commented
@alikirec fixed the typo and updated the readme with instruction to install parcel

2021-09-17 11:24 UTC, alikirec approved these changes

2021-09-17 16:50 UTC, fzembow approved these changes
LGTM

Btw, in case you were wondering, these files would _not_ be included when this package is used as a dependency, due to the `files` key in the `package.json` ([see docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files))

```
  "files": [
    "lib/**/*"
  ],
```

2021-09-17 16:50 UTC, merged